language: ruby
rvm:
- 2.3.1
install:
- bundle install
- gem install html-proofer
- gem install hunspell
# addons:
#   apt:
#     packages:
#     - hunspell
#     - libhunspell-dev
script:
- jekyll doctor && jekyll build --verbose
- hunspell --version
- hunspell -u3 -d en_US -H _site/**/*.html
- htmlproofer ./_site --check-html --allow-hash-href

# branch blacklist
branches:
  exclude:
  - gh-pages     # do not test the gh-pages branch

exclude: [vendor] # Travis bundles all gems in the vendor directory on its build servers, which Jekyll will mistakenly read and explode on.
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
sudo: false # explicitly build on Travis’s container-based infrastructure
dist: trusty
